require('nvim-treesitter.configs').setup {
    ensure_installed = {
      'bash',
      'c',
      'cpp',
      'css',
      'csv',
      'diff',
      'elixir',
      'erlang',
      'git_config',
      'git_rebase',
      'gitattributes',
      'gitcommit',
      'gitignore',
      'go',
      'gomod',
      'gosum',
      'gpg',
      'groovy',
      'html',
      'http',
      'ini',
      'java',
      'javascript',
      'jq',
      'json',
      'kotlin',
      'latex',
      'lua',
      'make',
      'markdown',
      'nix',
      'pem',
      'proto',
      'python',
      'rust',
      'terraform',
      'toml',
      'tsv',
      'vim',
      'vimdoc',
      'xml',
      'yaml',
    },
    sync_install = false,
    highlight = { enable = true },
    indent = { enable = false },
  }

